server:  
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CreditCardD12
    username: postgres
    password: 9063027
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update 
